### PR TITLE
Added support for PATCH

### PR DESCRIPTION
**Pull request by ehogberg**

### CODE REVIEW

**Comment by mhjort** [comment]
Thanks for the PR. Would it be possible for you to add the PATCH case to test suite too?

**Comment by ehogberg** [comment]
Just added it in.  Thanks for the quick review!

**Comment by mhjort** [comment]
Thanks! I merged this one and released new version `0.4.0`.

**Comment by ehogberg** [comment]
And thanks in turn; pulled it down and it’s working like a champ with the new method.  Appreciate the quick merge and the library in general; makes Lambda web server dev with Clojure tons easier.

**Pull request merged**
